type Committee = {
  name: string;
  description: string;
  agenda: string;
  backgroundGuideUrl: string | null;
  matrix: {
    portfolio: string;
    filled: boolean;
  }[];
  eb: {
    name: string;
    position: string;
    image: string;
  }[];
}

export const COMM_DATA: Record<
  'disec' | 'unhrc' | 'aippm' | 'ipc' | 'unsc' | 'icrc' | 'ccc',
  Committee
> = {
  disec: {
    name: 'DISEC',
    description: '',
    agenda: 'Regulating the Transfer and Use of Military Technologies by Non-State Actors',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: "Islamic Republic of Afghanistan", filled: true },
      { portfolio: "Republic of Argentina", filled: true },
      { portfolio: "Commonwealth of Australia", filled: true },
      { portfolio: "Republic of Austria", filled: true },
      { portfolio: "People’s Republic of Bangladesh", filled: true },
      { portfolio: "Kingdom of Belgium", filled: false },
      { portfolio: "Federative Republic of Brazil", filled: true },
      { portfolio: "Canada", filled: true },
      { portfolio: "Republic of Chile", filled: true },
      { portfolio: "People’s Republic of China", filled: false },
      { portfolio: "Republic of Colombia", filled: true },
      { portfolio: "Republic of Cuba", filled: true },
      { portfolio: "Czech Republic", filled: true },
      { portfolio: "Democratic People’s Republic of Korea", filled: true },
      { portfolio: "Kingdom of Denmark", filled: true },
      { portfolio: "Arab Republic of Egypt", filled: true },
      { portfolio: "Republic of Finland", filled: true },
      { portfolio: "French Republic", filled: true },
      { portfolio: "Federal Republic of Germany", filled: false },
      { portfolio: "Republic of Ghana", filled: true },
      { portfolio: "Hellenic Republic", filled: true },
      { portfolio: "Republic of India", filled: true },
      { portfolio: "Republic of Indonesia", filled: true },
      { portfolio: "Islamic Republic of Iran", filled: false },
      { portfolio: "Republic of Iraq", filled: true },
      { portfolio: "Ireland", filled: true },
      { portfolio: "State of Israel", filled: false },
      { portfolio: "Italian Republic", filled: true },
      { portfolio: "Japan", filled: false },
      { portfolio: "Republic of Kenya", filled: true },
      { portfolio: "State of Kuwait", filled: true },
      { portfolio: "Lebanese Republic", filled: true },
      { portfolio: "Malaysia", filled: true },
      { portfolio: "United Mexican States", filled: true },
      { portfolio: "Kingdom of Morocco", filled: true },
      { portfolio: "Kingdom of the Netherlands", filled: true },
      { portfolio: "New Zealand", filled: true },
      { portfolio: "Federal Republic of Nigeria", filled: true },
      { portfolio: "Kingdom of Norway", filled: true },
      { portfolio: "Islamic Republic of Pakistan", filled: false },
      { portfolio: "Republic of the Philippines", filled: true },
      { portfolio: "Republic of Poland", filled: true },
      { portfolio: "State of Qatar", filled: false },
      { portfolio: "Republic of Korea", filled: true },
      { portfolio: "Romania", filled: true },
      { portfolio: "Russian Federation", filled: false },
      { portfolio: "Kingdom of Saudi Arabia", filled: true },
      { portfolio: "Republic of Singapore", filled: true },
      { portfolio: "Federal Republic of Somalia", filled: true },
      { portfolio: "Republic of South Africa", filled: true },
      { portfolio: "Kingdom of Sweden", filled: true },
      { portfolio: "Swiss Confederation", filled: true },
      { portfolio: "Syrian Arab Republic", filled: false },
      { portfolio: "Kingdom of Thailand", filled: true },
      { portfolio: "Republic of Türkiye", filled: true },
      { portfolio: "Ukraine", filled: false },
      { portfolio: "United Arab Emirates", filled: true },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: true },
      { portfolio: "United States of America", filled: false },
      { portfolio: "Bolivarian Republic of Venezuela", filled: true },
      { portfolio: 'Socialist Republic of Viet Nam', filled: true },
      { portfolio: 'Republic of Yemen', filled: true },
      { portfolio: 'Republic of Zambia', filled: true },
      { portfolio: 'People’s Democratic Republic of Algeria', filled: false },
      { portfolio: 'Republic of Côte d’Ivoire', filled: true },
      { portfolio: 'Federal Democratic Republic of Ethiopia', filled: true },
      { portfolio: 'Hashemite Kingdom of Jordan', filled: false },
      { portfolio: 'State of Libya', filled: false },
      { portfolio: 'Republic of Mali', filled: true },
      { portfolio: 'Republic of Peru', filled: false },
      { portfolio: 'Republic of Senegal', filled: true },
      { portfolio: 'Kingdom of Spain', filled: true },
      { portfolio: 'Democratic Socialist Republic of Sri Lanka', filled: true },
      { portfolio: 'Republic of the Sudan', filled: true },
      { portfolio: 'Republic of Tunisia', filled: true },
    ],
    eb: [
      { name: 'Priyanshu Biswas', position: 'Co-Chairperson', image: '/assets/eb/disec/priyanshu.jpeg' },
      { name: 'Zaina Rao', position: 'Co-Chairperson', image: '/assets/eb/disec/zaina.jpeg' },
      { name: 'Aahil K', position: 'Vice-Chairperson', image: '/assets/eb/disec/aahil.png' },
    ]
  },

  unhrc: {
    name: 'UNHRC',
    description: '',
    agenda: 'Discussing the regulation of emerging Neurotechnologies in relation to mental integrity and autonomy.',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: "Argentine Republic", filled: true },
      { portfolio: "Federative Republic of Brazil", filled: true },
      { portfolio: "Republic of Ecuador", filled: true },
      { portfolio: "Republic of Paraguay", filled: true },
      { portfolio: "United Mexican States", filled: true },
      { portfolio: "United States of America", filled: true },
      { portfolio: "Canada", filled: true },
      { portfolio: "Republic of Guatemala", filled: true },
      { portfolio: "Republic of Costa Rica", filled: true },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: false },
      { portfolio: "Ireland", filled: true },
      { portfolio: "French Republic", filled: true },
      { portfolio: "Federal Republic of Germany", filled: true },
      { portfolio: "Kingdom of Spain", filled: true },
      { portfolio: "Italian Republic", filled: true },
      { portfolio: "Republic of Poland", filled: true },
      { portfolio: "Hungary", filled: true },
      { portfolio: "Romania", filled: false },
      { portfolio: "Ukraine", filled: true },
      { portfolio: "Kingdom of Sweden", filled: true },
      { portfolio: "Kingdom of Norway", filled: true },
      { portfolio: "Kingdom of the Netherlands", filled: true },
      { portfolio: "Kingdom of Belgium", filled: true },
      { portfolio: "Portuguese Republic", filled: true },
      { portfolio: "Republic of Türkiye", filled: true },
      { portfolio: "Russian Federation", filled: false },
      { portfolio: "Georgia", filled: true },
      { portfolio: "Republic of India", filled: false },
      { portfolio: "Islamic Republic of Pakistan", filled: false },
      { portfolio: "People's Republic of Bangladesh", filled: true },
      { portfolio: "Islamic Republic of Afghanistan", filled: true },
      { portfolio: "People's Republic of China", filled: false },
      { portfolio: "Japan", filled: true },
      { portfolio: "Republic of Korea", filled: true },
      { portfolio: "Republic of Indonesia", filled: true },
      { portfolio: "Malaysia", filled: true },
      { portfolio: "Republic of the Philippines", filled: true },
      { portfolio: "Kingdom of Thailand", filled: true },
      { portfolio: "Socialist Republic of Viet Nam", filled: true },
      { portfolio: "Arab Republic of Egypt", filled: true },
      { portfolio: "Kingdom of Morocco", filled: true },
      { portfolio: "Republic of the Sudan", filled: true },
      { portfolio: "Federal Democratic Republic of Ethiopia", filled: true },
      { portfolio: "Republic of Kenya", filled: false },
      { portfolio: "United Republic of Tanzania", filled: true },
      { portfolio: "Republic of South Africa", filled: true },
      { portfolio: "Federal Republic of Nigeria", filled: true },
      { portfolio: "Republic of Ghana", filled: true },
      { portfolio: "Kingdom of Saudi Arabia", filled: false },
      { portfolio: "Islamic Republic of Iran", filled: false },
      { portfolio: "State of Israel", filled: false },
      { portfolio: "New Zealand", filled: true },
      { portfolio: "Commonwealth of Australia", filled: true },
      { portfolio: "Swiss Confederation", filled: true },
      { portfolio: "Republic of Finland", filled: true },
      { portfolio: "Kingdom of Denmark", filled: true },
      { portfolio: "Republic of Singapore", filled: true },
      { portfolio: "United Arab Emirates", filled: true },
      { portfolio: "Republic of Maldives", filled: true },
      { portfolio: "Iceland", filled: true },
      { portfolio: 'Chile', filled: false },
      { portfolio: 'Colombia', filled: false },
      { portfolio: 'Peru', filled: false },
      { portfolio: 'Bolivia', filled: false },
      { portfolio: 'Uruguay', filled: false },
      { portfolio: 'Honduras', filled: false },
      { portfolio: 'El Salvador', filled: true },
      { portfolio: 'Nicaragua', filled: false },
      { portfolio: 'Panama', filled: false },
      { portfolio: 'Nepal', filled: true },
      { portfolio: 'Sri Lanka', filled: true },
      { portfolio: 'Algeria', filled: false },
      { portfolio: 'Tunisia', filled: true },
      { portfolio: 'Libya', filled: false },
      { portfolio: 'Uganda', filled: false },
      { portfolio: 'Rwanda', filled: false },
      { portfolio: 'Senegal', filled: true },
      { portfolio: 'Jordan', filled: true },
      { portfolio: 'Mauritius', filled: false },
      { portfolio: 'Fiji', filled: false },
    ],
    eb: [
      { name: 'Aabid Maldar', position: 'Co-Chairperson', image: '/assets/eb/unhrc/aabid.png' },
      { name: 'Yeshwanth Reddy', position: 'Co-Chairperson', image: '/assets/eb/unhrc/yeshwanth.jpeg' },
      { name: 'Devyansh Behera', position: 'Vice-Chairperson', image: '/assets/eb/unhrc/devyansh.png' },
    ],
  },

  aippm: {
    name: 'AIPPM',
    description: '',
    agenda: 'Deliberating upon the electoral landscape in India with reference to the upcoming census and subsequent delimitation',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: "Narendra Modi", filled: false },
      { portfolio: "Amit Shah", filled: true },
      { portfolio: "Tejasvi Surya", filled: false },
      { portfolio: "Arjun Ram Meghwal", filled: false },
      { portfolio: "Kiren Rijju", filled: true },
      { portfolio: "Dr. C.N Manjunath", filled: false },
      { portfolio: "Nitin Gadkari", filled: true },
      { portfolio: "Nishikant Dubey", filled: false },
      { portfolio: "Piyush Goyal", filled: false },
      { portfolio: "Jyotiraditya Scindia", filled: false },
      { portfolio: "Gajendra Singh Shekhawat", filled: false },
      { portfolio: "Chirag Paswan", filled: true },
      { portfolio: "Hardeep Singh Puri", filled: false },
      { portfolio: "Rajnath Singh", filled: false },
      { portfolio: "H. D. Kumaraswamy", filled: true },
      { portfolio: "Dharmendra Pradhan", filled: false },
      { portfolio: "Shivraj Singh Chouhan", filled: true },
      { portfolio: "Mansukh L. Mandaviya", filled: true },
      { portfolio: "Ashwini Vaishnaw", filled: true },
      { portfolio: "Rahul Gandhi", filled: false },
      { portfolio: "Dr. Shashi Tharoor", filled: true },
      { portfolio: "Gaurav Gogoi", filled: true },
      { portfolio: "K.C Venugopal", filled: true },
      { portfolio: "Priyanka Gandhi Vadra", filled: true },
      { portfolio: "Charanjit Singh Channi", filled: true },
      { portfolio: "Karti P Chidambaram", filled: true },
      { portfolio: "Manish Tewari", filled: true },
      { portfolio: "Mahua Moitra", filled: true },
      { portfolio: "Kanimozhi Karunanidhi", filled: true },
      { portfolio: "Dayanidhi Maran", filled: true },
      { portfolio: "Supriya Sule", filled: true },
      { portfolio: "Akhilesh Yadav", filled: true },
      { portfolio: "Asaduddin Owaisi", filled: true },
      { portfolio: "Arvind Sawant", filled: true },
      { portfolio: "E.T Mohammed Basheer", filled: true },
      { portfolio: "Pappu Yadav", filled: true },
      { portfolio: "Aga syed Ruhullah Mehdi", filled: true },
      { portfolio: "A.M Ariff", filled: true },
      { portfolio: "Muhammed Hamdullah Syed", filled: true },
      { portfolio: "Deepender Singh Hooda", filled: true },
      { portfolio: 'Joseph Vijay Chandrasekhar', filled: true },
      { portfolio: 'N. Chandrababu Naidu', filled: false },
      { portfolio: 'Revanth Reddy', filled: false },
      { portfolio: 'D. K. Shivakumar', filled: false },
      { portfolio: 'Yogi Adityanath', filled: false },
      { portfolio: 'Nitish Kumar', filled: true },
      { portfolio: 'Mamata Banerjee', filled: false },
      { portfolio: 'Himanta Biswa Sarma', filled: false },
      { portfolio: 'Suvendu Adhikari', filled: true },
      { portfolio: 'Nirmala Sitharaman', filled: false },
      { portfolio: 'J. P. Nadda', filled: false },
      { portfolio: 'Sudhanshu Trivedi', filled: true },
      { portfolio: 'Sonia Gandhi', filled: true },
      { portfolio: 'Mallikarjun Kharge', filled: true },
      { portfolio: 'Jairam Ramesh', filled: false },
      { portfolio: 'Abhishek Manu Singhvi', filled: false },
      { portfolio: 'Kanhaiya Kumar', filled: true },
      { portfolio: 'Farooq Abdullah', filled: true },
      { portfolio: 'Sharad Pawar', filled: false },
      { portfolio: 'Uddhav Thackeray', filled: true },
      { portfolio: 'Eknath Shinde', filled: true },
      { portfolio: 'Arvind Kejriwal', filled: true },
      { portfolio: 'Raghav Chadha', filled: true },
    ],
    eb: [
      { name: 'Manav Dharia', position: 'Co-Chairperson', image: '/assets/eb/aippm/manav.jpeg' },
      { name: 'Aarav Motreja', position: 'Co-Chairperson', image: '/assets/eb/aippm/aarav.jpeg' },
      { name: 'Kavin Saraf', position: 'Vice-Chairperson', image: '/assets/eb/aippm/kavin.jpeg' },
    ],
  },

  ipc: {
    name: 'IPC',
    description: '',
    agenda: 'No Agenda',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: "The Washington Post", filled: false },
      { portfolio: "The Economist", filled: false },
      { portfolio: "National Review", filled: true },
      { portfolio: "Al Jazeera", filled: true },
      { portfolio: "The Hindu", filled: false },
      { portfolio: "BBC", filled: false },
      { portfolio: "TASS", filled: true },
      { portfolio: "African News Agency", filled: true },
      { portfolio: "Reuters", filled: true },
      { portfolio: "The New York Times", filled: true },
      { portfolio: "The Daily Telegraph", filled: true },
      { portfolio: "The Wall Street Journal", filled: true },
      { portfolio: "Sankei Shimbun", filled: true },
      { portfolio: "Bloomberg", filled: true },
      { portfolio: "The Deccan Herald", filled: true },
      { portfolio: "Reason", filled: true },
      { portfolio: "Times of India", filled: false },
      { portfolio: "Doordarshan", filled: false },
      { portfolio: "Saamna", filled: true },
      { portfolio: "Bombay Samachar", filled: true },
      { portfolio: 'The Jacobin', filled: true },
      { portfolio: 'Mother Jones', filled: false },
      { portfolio: 'The Daily Wire', filled: true },
      { portfolio: 'Vox', filled: false },
      { portfolio: 'The Atlantic', filled: false },
      { portfolio: 'Le Figaro', filled: false },
      { portfolio: 'Junge Freiheit', filled: true },
      { portfolio: 'Neue Zürcher Zeitung', filled: false },
      { portfolio: 'El Mercurio', filled: true },
    ],
    eb: [
      { name: 'Shanmukha Siva Mythreya', position: 'International Head of Press', image: '/assets/eb/ipc/shanmukha.jpeg' },
      { name: 'Kapishnu P.K.', position: 'Assistant Head of Press', image: '/assets/eb/ipc/kapishnu.jpeg' },
    ],
  },

  unsc: {
    name: 'UNSC',
    description: '',
    agenda: 'De-escalation of US-Iran War with special emphasis on the Strait of Hormuz Freeze date: June 7, 2026, Israeli strikes on Hezbollah',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: "United States of America", filled: true },
      { portfolio: "People's Republic of China", filled: true },
      { portfolio: "French Republic", filled: true },
      { portfolio: "Russian Federation", filled: true },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: false },
      { portfolio: "Islamic Republic of Iran", filled: true },
      { portfolio: "State of Israel", filled: true },
      { portfolio: "Kingdom of Saudi Arabia", filled: true },
      { portfolio: "United Arab Emirates", filled: true },
      { portfolio: "Sultanate of Oman", filled: true },
      { portfolio: "State of Qatar", filled: true },
      { portfolio: "State of Kuwait", filled: true },
      { portfolio: "Republic of Iraq", filled: false },
      { portfolio: "Islamic Republic of Pakistan", filled: true },
      { portfolio: "Republic of India", filled: true },
      { portfolio: 'Japan', filled: false },
      { portfolio: 'Greece', filled: false },
      { portfolio: 'Denmark', filled: false },
      { portfolio: 'Somalia', filled: false },
      { portfolio: 'Panama', filled: false },
      { portfolio: 'Algeria', filled: false },
      { portfolio: 'Sierra Leone', filled: true },
      { portfolio: 'Guyana', filled: false },
      { portfolio: 'Bahrain', filled: true },
      { portfolio: 'Lebanon', filled: false },
      { portfolio: 'Turkey', filled: true },
      { portfolio: 'South Korea', filled: true },
      { portfolio: 'Singapore', filled: false },
      { portfolio: 'Egypt', filled: false },
      { portfolio: 'Italy', filled: false },
    ],
    eb: [
      { name: 'Eshaan Chowdary', position: 'Head-Chairperson', image: '/assets/eb/unsc/eshaan.jpeg' },
      { name: 'Jishnu Adidam', position: 'Vice-Chairperson', image: '/assets/eb/unsc/jishnu.jpeg' },
      { name: 'Aarav Sinha', position: 'Vice-Chairperson', image: '/assets/eb/unsc/aarav.jpeg' },
    ],
  },

  icrc: {
    name: 'ICRC',
    description: '',
    agenda: 'Examining the Role of the International Committee of the Red Cross in Providing Humanitarian Assistance and Protection to Civilians in the Gaza Strip',
    backgroundGuideUrl: "https://drive.google.com/drive/folders/1ml1SUkXW5IuyH_oi_0ixQNsjBhzRqu1B?usp=sharing",
    matrix: [
      { portfolio: 'State of Israel', filled: false },
      { portfolio: 'State of Palestine', filled: false },
      { portfolio: 'Hamas (non-UN entity)', filled: true },
      { portfolio: 'Arab Republic of Egypt', filled: false },
      { portfolio: 'Hashemite Kingdom of Jordan', filled: true },
      { portfolio: 'Lebanese Republic', filled: true },
      { portfolio: 'United States of America', filled: true },
      { portfolio: 'Kingdom of Saudi Arabia', filled: true },
      { portfolio: 'French Republic', filled: false },
      { portfolio: 'Russian Federation', filled: true },
      {
        portfolio: "People's Republic of China", filled: false
      },
      { portfolio: 'State of Qatar', filled: true },
      { portfolio: 'United Kingdom of Great Britain and Northern Ireland', filled: false },
      { portfolio: 'United Arab Emirates', filled: true },
      { portfolio: 'Republic of Türkiye', filled: true },
      { portfolio: 'Islamic Republic of Iran', filled: false },
      { portfolio: 'State of Kuwait', filled: true },
      { portfolio: 'Kingdom of Bahrain', filled: true },
      { portfolio: 'Sultanate of Oman', filled: true },
      { portfolio: 'Republic of Iraq', filled: true },
      { portfolio: 'Syrian Arab Republic', filled: true },
      { portfolio: 'Federal Republic of Germany', filled: true },
      { portfolio: 'Italian Republic', filled: true },
      { portfolio: 'Kingdom of Spain', filled: true },
      { portfolio: 'Kingdom of the Netherlands', filled: true },
      { portfolio: 'Belgium', filled: true },
      { portfolio: 'Sweden', filled: false },
      { portfolio: 'Norway', filled: true },
      { portfolio: 'Switzerland', filled: true },
      { portfolio: 'Ireland', filled: true },
      { portfolio: 'India', filled: true },
      { portfolio: 'Pakistan', filled: true },
      { portfolio: 'Indonesia', filled: true },
      { portfolio: 'Malaysia', filled: true },
      { portfolio: 'Bangladesh', filled: true },
      { portfolio: 'Canada', filled: true },
      { portfolio: 'Japan', filled: true },
      { portfolio: 'Australia', filled: true },
      { portfolio: 'South Africa', filled: false },
      { portfolio: 'Brazil', filled: true },
    ],
    eb: [
      { name: 'Brihan Shankar', position: 'Head-Chairperson', image: '/assets/eb/icrc/brihan.jpeg' },
      { name: 'Arul S.', position: 'Vice-Chairperson', image: '/assets/eb/icrc/arul.jpeg' },
      { name: 'Harsha Aditya', position: 'Vice-Chairperson', image: '/assets/eb/icrc/harsha.jpeg' },
    ],
  },

  ccc: {
    name: 'CCC',
    description: '',
    agenda: 'Combating the Bombay Syndicate (Freeze Date - 12th March, 1993 (0800 hours))',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "Dawood Ibrahim", filled: true },
      { portfolio: "Ibrahim “Tiger” Memon", filled: false },
      { portfolio: "Chhota Rajan", filled: false },
      { portfolio: "Arun Gawli", filled: false },
      { portfolio: "Amar Naik", filled: true },
      { portfolio: "S.Ramamurti", filled: true },
      { portfolio: "Shreekant Bapat", filled: false },
      { portfolio: "Sharad Pawar", filled: true },
      { portfolio: "P.C.Alexander", filled: true },
      { portfolio: "Bal Thackeray", filled: true },
      { portfolio: "Gopinath Munde", filled: false },
      { portfolio: "K.S.Sudarshan", filled: false },
      { portfolio: "S.B.Chavan", filled: true },
      { portfolio: "M.K.Narayanan", filled: false },
      { portfolio: "S.Subramanyam", filled: false },
      { portfolio: "Dilip Kumar", filled: true },
      { portfolio: "Sunit Khatau", filled: true },
      { portfolio: "Datta Samant", filled: true },
      { portfolio: "Lt.Gen.Javed Nasir", filled: true },
      { portfolio: "Haseena Parkar", filled: true },
      { portfolio: "Babu Reshim", filled: true },
      { portfolio: "Ashwin Naik", filled: true },
      { portfolio: "A.A.Khan", filled: true },
      { portfolio: "P.V.Narasimha Rao", filled: false },
      { portfolio: "Bharat Shah", filled: true },
      { portfolio: 'Anees Ibrahim Kaskar', filled: false },
      { portfolio: 'Chhota Shakeel', filled: false },
      { portfolio: 'Abu Salem', filled: false },
      { portfolio: 'Sharad Shetty', filled: false },
      { portfolio: 'Shabir Ibrahim Kaskar', filled: false },
      { portfolio: 'Sada Pawle', filled: true },
      { portfolio: 'Rakesh Maria', filled: false },
      { portfolio: 'Madhukar Zende', filled: false },
      { portfolio: 'Chandrakant Handore', filled: false },
      { portfolio: 'D.M. Sukthankar', filled: false },
      { portfolio: 'Shivajirao Deshmukh', filled: false },
      { portfolio: 'N. Vittal', filled: false },
      { portfolio: 'Manohar Joshi', filled: false },
      { portfolio: 'Hitendra Thakur', filled: false },
      { portfolio: 'N.N. Vohra', filled: false },
      { portfolio: 'A.S. Syali', filled: false },
      { portfolio: 'R.P. Singh', filled: false },
      { portfolio: 'Gulshan Kumar', filled: false },
      { portfolio: 'Sanjay Dutt', filled: false },
      { portfolio: 'Jackie Shroff', filled: true },
      { portfolio: 'Subhash Ghai', filled: false },
      { portfolio: 'Nusli Wadia', filled: false },
      { portfolio: 'Pallonji Mistry', filled: false },
      { portfolio: 'Haribhau Naik', filled: true },
      { portfolio: 'Haji Mastan', filled: false },
    ],
    eb: [
      { name: 'Jay R.', position: 'Head-Chairperson', image: '/assets/eb/ccc/jay.jpeg' },
      { name: 'Parthiv Dileep', position: 'Vice-Chairperson', image: '/assets/eb/ccc/parthiv.jpeg' },
      { name: 'Arnav Yadav', position: 'Moderator', image: '/assets/eb/ccc/arnav.jpeg' },
    ],
  },
}
