type Committee = {
  name: string;
  description: string;
  agenda: string;
  backgroundGuideUrl: string | null;
  matrix: {
    portfolio: string;
    filled: boolean;
  }[];
  eb: {
    name: string;
    position: string;
    image: string;
  }[];
}

export const COMM_DATA: Record<
  'disec' | 'unhrc' | 'aippm' | 'ipc' | 'unsc' | 'icrc' | 'ccc',
  Committee
> = {
  disec: {
    name: 'DISEC',
    description: '',
    agenda: 'Regulating the Transfer and Use of Military Technologies by Non-State Actors',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "Islamic Republic of Afghanistan", filled: false },
      { portfolio: "Republic of Argentina", filled: false },
      { portfolio: "Commonwealth of Australia", filled: false },
      { portfolio: "Republic of Austria", filled: false },
      { portfolio: "People’s Republic of Bangladesh", filled: false },
      { portfolio: "Kingdom of Belgium", filled: false },
      { portfolio: "Federative Republic of Brazil", filled: false },
      { portfolio: "Canada", filled: false },
      { portfolio: "Republic of Chile", filled: false },
      { portfolio: "People’s Republic of China", filled: false },
      { portfolio: "Republic of Colombia", filled: false },
      { portfolio: "Republic of Cuba", filled: false },
      { portfolio: "Czech Republic", filled: false },
      { portfolio: "Democratic People’s Republic of Korea", filled: false },
      { portfolio: "Kingdom of Denmark", filled: false },
      { portfolio: "Arab Republic of Egypt", filled: false },
      { portfolio: "Republic of Finland", filled: false },
      { portfolio: "French Republic", filled: false },
      { portfolio: "Federal Republic of Germany", filled: false },
      { portfolio: "Republic of Ghana", filled: false },
      { portfolio: "Hellenic Republic", filled: false },
      { portfolio: "Republic of India", filled: false },
      { portfolio: "Republic of Indonesia", filled: false },
      { portfolio: "Islamic Republic of Iran", filled: false },
      { portfolio: "Republic of Iraq", filled: false },
      { portfolio: "Ireland", filled: false },
      { portfolio: "State of Israel", filled: false },
      { portfolio: "Italian Republic", filled: false },
      { portfolio: "Japan", filled: false },
      { portfolio: "Republic of Kenya", filled: false },
      { portfolio: "State of Kuwait", filled: false },
      { portfolio: "Lebanese Republic", filled: false },
      { portfolio: "Malaysia", filled: false },
      { portfolio: "United Mexican States", filled: false },
      { portfolio: "Kingdom of Morocco", filled: false },
      { portfolio: "Kingdom of the Netherlands", filled: false },
      { portfolio: "New Zealand", filled: false },
      { portfolio: "Federal Republic of Nigeria", filled: false },
      { portfolio: "Kingdom of Norway", filled: false },
      { portfolio: "Islamic Republic of Pakistan", filled: false },
      { portfolio: "Republic of the Philippines", filled: false },
      { portfolio: "Republic of Poland", filled: false },
      { portfolio: "State of Qatar", filled: false },
      { portfolio: "Republic of Korea", filled: false },
      { portfolio: "Romania", filled: false },
      { portfolio: "Russian Federation", filled: false },
      { portfolio: "Kingdom of Saudi Arabia", filled: false },
      { portfolio: "Republic of Singapore", filled: false },
      { portfolio: "Federal Republic of Somalia", filled: false },
      { portfolio: "Republic of South Africa", filled: false },
      { portfolio: "Kingdom of Sweden", filled: false },
      { portfolio: "Swiss Confederation", filled: false },
      { portfolio: "Syrian Arab Republic", filled: false },
      { portfolio: "Kingdom of Thailand", filled: false },
      { portfolio: "Republic of Türkiye", filled: false },
      { portfolio: "Ukraine", filled: false },
      { portfolio: "United Arab Emirates", filled: false },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: false },
      { portfolio: "United States of America", filled: false },
      { portfolio: "Bolivarian Republic of Venezuela", filled: false },
    ],
    eb: [
      { name: 'Priyanshu Biswas', position: 'Co-Chairperson', image: '/assets/eb/disec/priyanshu.jpeg' },
      { name: 'Zaina Rao', position: 'Co-Chairperson', image: '/assets/eb/disec/zaina.jpeg' },
      { name: 'Aahil K', position: 'Vice-Chairperson', image: '/assets/eb/disec/aahil.png' },
    ]
  },

  unhrc: {
    name: 'UNHRC',
    description: '',
    agenda: 'Discussing the regulation of emerging Neurotechnologies in relation to mental integrity and autonomy.',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "Argentine Republic", filled: false },
      { portfolio: "Federative Republic of Brazil", filled: false },
      { portfolio: "Republic of Ecuador", filled: false },
      { portfolio: "Republic of Paraguay", filled: false },
      { portfolio: "United Mexican States", filled: false },
      { portfolio: "United States of America", filled: false },
      { portfolio: "Canada", filled: false },
      { portfolio: "Republic of Guatemala", filled: false },
      { portfolio: "Republic of Costa Rica", filled: false },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: false },
      { portfolio: "Ireland", filled: false },
      { portfolio: "French Republic", filled: false },
      { portfolio: "Federal Republic of Germany", filled: false },
      { portfolio: "Kingdom of Spain", filled: false },
      { portfolio: "Italian Republic", filled: false },
      { portfolio: "Republic of Poland", filled: false },
      { portfolio: "Hungary", filled: false },
      { portfolio: "Romania", filled: false },
      { portfolio: "Ukraine", filled: false },
      { portfolio: "Kingdom of Sweden", filled: false },
      { portfolio: "Kingdom of Norway", filled: false },
      { portfolio: "Kingdom of the Netherlands", filled: false },
      { portfolio: "Kingdom of Belgium", filled: false },
      { portfolio: "Portuguese Republic", filled: false },
      { portfolio: "Republic of Türkiye", filled: false },
      { portfolio: "Russian Federation", filled: false },
      { portfolio: "Georgia", filled: false },
      { portfolio: "Republic of India", filled: false },
      { portfolio: "Islamic Republic of Pakistan", filled: false },
      { portfolio: "People's Republic of Bangladesh", filled: false },
      { portfolio: "Islamic Republic of Afghanistan", filled: false },
      { portfolio: "People's Republic of China", filled: false },
      { portfolio: "Japan", filled: false },
      { portfolio: "Republic of Korea", filled: false },
      { portfolio: "Republic of Indonesia", filled: false },
      { portfolio: "Malaysia", filled: false },
      { portfolio: "Republic of the Philippines", filled: false },
      { portfolio: "Kingdom of Thailand", filled: false },
      { portfolio: "Socialist Republic of Viet Nam", filled: false },
      { portfolio: "Arab Republic of Egypt", filled: false },
      { portfolio: "Kingdom of Morocco", filled: false },
      { portfolio: "Republic of the Sudan", filled: false },
      { portfolio: "Federal Democratic Republic of Ethiopia", filled: false },
      { portfolio: "Republic of Kenya", filled: false },
      { portfolio: "United Republic of Tanzania", filled: false },
      { portfolio: "Republic of South Africa", filled: false },
      { portfolio: "Federal Republic of Nigeria", filled: false },
      { portfolio: "Republic of Ghana", filled: false },
      { portfolio: "Kingdom of Saudi Arabia", filled: false },
      { portfolio: "Islamic Republic of Iran", filled: false },
      { portfolio: "State of Israel", filled: false },
      { portfolio: "New Zealand", filled: false },
      { portfolio: "Commonwealth of Australia", filled: false },
      { portfolio: "Swiss Confederation", filled: false },
      { portfolio: "Republic of Finland", filled: false },
      { portfolio: "Kingdom of Denmark", filled: false },
      { portfolio: "Republic of Singapore", filled: false },
      { portfolio: "United Arab Emirates", filled: false },
      { portfolio: "Republic of Maldives", filled: false },
      { portfolio: "Iceland", filled: false },
    ],
    eb: [
      { name: 'Aabid Maldar', position: 'Co-Chairperson', image: '/assets/eb/unhrc/aabid.png' },
      { name: 'Yeshwanth Reddy', position: 'Co-Chairperson', image: '/assets/eb/unhrc/yeshwanth.jpeg' },
      { name: 'Ashlin Jermine George', position: 'Vice-Chairperson', image: '/assets/eb/unhrc/ashlin.jpeg' },
      { name: 'Devyansh Behera', position: 'Moderator', image: '/assets/eb/unhrc/devyansh.png' },
    ],
  },

  aippm: {
    name: 'AIPPM',
    description: '',
    agenda: 'Deliberating upon the electoral landscape in India with reference to the upcoming census and subsequent delimitation',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "Narendra Modi", filled: false },
      { portfolio: "Amit Shah", filled: false },
      { portfolio: "Tejasvi Surya", filled: false },
      { portfolio: "Arjun Ram Meghwal", filled: false },
      { portfolio: "Kiren Rijju", filled: false },
      { portfolio: "Dr. C.N Manjunath", filled: false },
      { portfolio: "Nitin Gadkari", filled: false },
      { portfolio: "Nishikant Dubey", filled: false },
      { portfolio: "Piyush Goyal", filled: false },
      { portfolio: "Jyotiraditya Scindia", filled: false },
      { portfolio: "Gajendra Singh Shekhawat", filled: false },
      { portfolio: "Chirag Paswan", filled: false },
      { portfolio: "Hardeep Singh Puri", filled: false },
      { portfolio: "Rajnath Singh", filled: false },
      { portfolio: "H. D. Kumaraswamy", filled: false },
      { portfolio: "Dharmendra Pradhan", filled: false },
      { portfolio: "Shivraj Singh Chouhan", filled: false },
      { portfolio: "Mansukh L. Mandaviya", filled: false },
      { portfolio: "Ashwini Vaishnaw", filled: false },
      { portfolio: "Rahul Gandhi", filled: false },
      { portfolio: "Dr. Shashi Tharoor", filled: false },
      { portfolio: "Gaurav Gogoi", filled: false },
      { portfolio: "K.C Venugopal", filled: false },
      { portfolio: "Priyanka Gandhi Vadra", filled: false },
      { portfolio: "Charanjit Singh Channi", filled: false },
      { portfolio: "Karti P Chidambaram", filled: false },
      { portfolio: "Manish Tewari", filled: false },
      { portfolio: "Mahua Moitra", filled: false },
      { portfolio: "Kanimozhi Karunanidhi", filled: false },
      { portfolio: "Dayanidhi Maran", filled: false },
      { portfolio: "Supriya Sule", filled: false },
      { portfolio: "Akhilesh Yadav", filled: false },
      { portfolio: "Asaduddin Owaisi", filled: false },
      { portfolio: "Arvind Sawant", filled: false },
      { portfolio: "E.T Mohammed Basheer", filled: false },
      { portfolio: "Pappu Yadav", filled: false },
      { portfolio: "Aga syed Ruhullah Mehdi", filled: false },
      { portfolio: "A.M Ariff", filled: false },
      { portfolio: "Muhammed Hamdullah Syed", filled: false },
      { portfolio: "Deepender Singh Hooda", filled: false },
    ],
    eb: [
      { name: 'Manav Dharia', position: 'Co-Chairperson', image: '/assets/eb/aippm/manav.jpeg' },
      { name: 'Aarav Motreja', position: 'Co-Chairperson', image: '/assets/eb/aippm/aarav.jpeg' },
      { name: 'Kavin Saraf', position: 'Vice-Chairperson', image: '/assets/eb/aippm/kavin.jpeg' },
    ],
  },

  ipc: {
    name: 'IPC',
    description: '',
    agenda: 'No Agenda.',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "The Washington Post", filled: false },
      { portfolio: "The Economist", filled: false },
      { portfolio: "National Review", filled: false },
      { portfolio: "Al Jazeera", filled: false },
      { portfolio: "The Hindu", filled: false },
      { portfolio: "BBC", filled: false },
      { portfolio: "TASS", filled: false },
      { portfolio: "African News Agency", filled: false },
      { portfolio: "Reuters", filled: false },
      { portfolio: "The New York Times", filled: false },
      { portfolio: "The Daily Telegraph", filled: false },
      { portfolio: "The Wall Street Journal", filled: false },
      { portfolio: "Sankei Shimbun", filled: false },
      { portfolio: "Bloomberg", filled: false },
      { portfolio: "The Deccan Herald", filled: false },
      { portfolio: "Reason", filled: false },
      { portfolio: "Times of India", filled: false },
      { portfolio: "Doordarshan", filled: false },
      { portfolio: "Saamna", filled: false },
      { portfolio: "Bombay Samachar", filled: false },
    ],
    eb: [
      { name: 'Shanmukha Siva Mythreya', position: 'International Head of Press', image: '/assets/eb/ipc/shanmukha.jpeg' },
      { name: 'Kapishnu P.K.', position: 'Assistant Head of Press', image: '/assets/eb/ipc/kapishnu.jpeg' },
    ],
  },

  unsc: {
    name: 'UNSC',
    description: '',
    agenda: 'De-escalation of US-Iran War with special emphasis on the Strait of Hormuz Freeze date: June 7, 2026, Israeli strikes on Hezbollah',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "United States of America", filled: false },
      { portfolio: "People's Republic of China", filled: false },
      { portfolio: "French Republic", filled: false },
      { portfolio: "Russian Federation", filled: false },
      { portfolio: "United Kingdom of Great Britain and Northern Ireland", filled: false },
      { portfolio: "Islamic Republic of Iran", filled: false },
      { portfolio: "State of Israel", filled: false },
      { portfolio: "Kingdom of Saudi Arabia", filled: false },
      { portfolio: "United Arab Emirates", filled: false },
      { portfolio: "Sultanate of Oman", filled: false },
      { portfolio: "State of Qatar", filled: false },
      { portfolio: "State of Kuwait", filled: false },
      { portfolio: "Republic of Iraq", filled: false },
      { portfolio: "Islamic Republic of Pakistan", filled: false },
      { portfolio: "Republic of India", filled: false },
    ],
    eb: [
      { name: 'Eshaan Chowdary', position: 'Head-Chairperson', image: '/assets/eb/unsc/eshaan.jpeg' },
      { name: 'Jishnu Adidam', position: 'Vice-Chairperson', image: '/assets/eb/unsc/jishnu.jpeg' },
      { name: 'Aarav Sinha', position: 'Vice-Chairperson', image: '/assets/eb/unsc/aarav.jpeg' },
    ],
  },

  icrc: {
    name: 'ICRC',
    description: '',
    agenda: 'Examining the Role of the International Committee of the Red Cross in Providing Humanitarian Assistance and Protection to Civilians in the Gaza Strip',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'State of Israel', filled: false },
      { portfolio: 'State of Palestine', filled: false },
      { portfolio: 'Hamas (non-UN entity)', filled: false },
      { portfolio: 'Arab Republic of Egypt', filled: false },
      { portfolio: 'Hashemite Kingdom of Jordan', filled: false },
      { portfolio: 'Lebanese Republic', filled: false },
      { portfolio: 'United States of America', filled: false },
      { portfolio: 'Kingdom of Saudi Arabia', filled: false },
      { portfolio: 'French Republic', filled: false },
      { portfolio: 'Russian Federation', filled: false },
      {
        portfolio: "People's Republic of China", filled: false
      },
      { portfolio: 'State of Qatar', filled: false },
      { portfolio: 'United Kingdom of Great Britain and Northern Ireland', filled: false },
      { portfolio: 'United Arab Emirates', filled: false },
      { portfolio: 'Republic of Türkiye', filled: false },
      { portfolio: 'Islamic Republic of Iran', filled: false },
      { portfolio: 'State of Kuwait', filled: false },
      { portfolio: 'Kingdom of Bahrain', filled: false },
      { portfolio: 'Sultanate of Oman', filled: false },
      { portfolio: 'Republic of Iraq', filled: false },
      { portfolio: 'Syrian Arab Republic', filled: false },
      { portfolio: 'Federal Republic of Germany', filled: false },
      { portfolio: 'Italian Republic', filled: false },
      { portfolio: 'Kingdom of Spain', filled: false },
      { portfolio: 'Kingdom of the Netherlands', filled: false },
    ],
    eb: [
      { name: 'Brihan Shankar', position: 'Head-Chairperson', image: '/assets/eb/icrc/brihan.jpeg' },
      { name: 'Arul S.', position: 'Vice-Chairperson', image: '/assets/eb/icrc/arul.jpeg' },
      { name: 'Harsha Aditya', position: 'Vice-Chairperson', image: '/assets/eb/icrc/harsha.jpeg' },
    ],
  },

  ccc: {
    name: 'CCC',
    description: '',
    agenda: 'Combating the Bombay Syndicate (Freeze Date - 12th March, 1993 (0800 hours))',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: "Dawood Ibrahim", filled: false },
      { portfolio: "Ibrahim “Tiger” Memon", filled: false },
      { portfolio: "Chhota Rajan", filled: false },
      { portfolio: "Arun Gawli", filled: false },
      { portfolio: "Amar Naik", filled: false },
      { portfolio: "S.Ramamurti", filled: false },
      { portfolio: "Shreekant Bapat", filled: false },
      { portfolio: "Sharad Pawar", filled: false },
      { portfolio: "P.C.Alexander", filled: false },
      { portfolio: "Bal Thackeray", filled: false },
      { portfolio: "Gopinath Munde", filled: false },
      { portfolio: "K.S.Sudarshan", filled: false },
      { portfolio: "S.B.Chavan", filled: false },
      { portfolio: "M.K.Narayanan", filled: false },
      { portfolio: "S.Subramanyam", filled: false },
      { portfolio: "Dilip Kumar", filled: false },
      { portfolio: "Sunit Khatau", filled: false },
      { portfolio: "Datta Samant", filled: false },
      { portfolio: "Lt.Gen.Javed Nasir", filled: false },
      { portfolio: "Haseena Parkar", filled: false },
      { portfolio: "Babu Reshim", filled: false },
      { portfolio: "Ashwin Naik", filled: false },
      { portfolio: "A.A.Khan", filled: false },
      { portfolio: "P.V.Narasimha Rao", filled: false },
      { portfolio: "Bharat Shah", filled: false },
    ],
    eb: [
      { name: 'Jay R.', position: 'Head-Chairperson', image: '/assets/eb/ccc/jay.jpeg' },
      { name: 'Parthiv Dileep', position: 'Vice-Chairperson', image: '/assets/eb/ccc/parthiv.jpeg' },
      { name: 'Arnav Yadav', position: 'Moderator', image: '/assets/eb/ccc/arnav.jpeg' },
    ],
  },
}
