type Committee = {
  name: string;
  description: string;
  agenda: string;
  backgroundGuideUrl: string | null;
  matrix: {
    portfolio: string;
    filled: boolean;
  }[];
  eb: {
    name: string;
    position: string;
    image: string;
  }[];
}

export const COMM_DATA: Record<
  'disec' | 'unhrc' | 'aippm' | 'ipc' | 'unsc' | 'icrc' | 'ccc',
  Committee
> = {
  disec: {
    name: 'DISEC',
    description: '',
    agenda: 'Regulating the Transfer and Use of Military Technologies by Non-State Actors',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'Islamic Republic of Afghanistan', filled: false },
      { portfolio: 'People’s Democratic Republic of Algeria', filled: false },
      { portfolio: 'Republic of Argentina', filled: false },
      { portfolio: 'Commonwealth of Australia', filled: false },
      { portfolio: 'Republic of Austria', filled: false },
      { portfolio: 'People’s Republic of Bangladesh', filled: false },
      { portfolio: 'Kingdom of Belgium', filled: false },
      { portfolio: 'Federative Republic of Brazil', filled: false },
      { portfolio: 'Canada', filled: false },
      { portfolio: 'Republic of Chile', filled: false },
      { portfolio: 'People’s Republic of China', filled: false },
      { portfolio: 'Republic of Colombia', filled: false },
      { portfolio: 'Republic of Côte d’Ivoire', filled: false },
      { portfolio: 'Republic of Cuba', filled: false },
      { portfolio: 'Czech Republic', filled: false },
      { portfolio: 'Democratic People’s Republic of Korea', filled: false },
      { portfolio: 'Kingdom of Denmark', filled: false },
      { portfolio: 'Arab Republic of Egypt', filled: false },
      { portfolio: 'Federal Democratic Republic of Ethiopia', filled: false },
      { portfolio: 'Republic of Finland', filled: false },
      { portfolio: 'French Republic', filled: false },
      { portfolio: 'Federal Republic of Germany', filled: false },
      { portfolio: 'Republic of Ghana', filled: false },
      { portfolio: 'Hellenic Republic', filled: false },
      { portfolio: 'Republic of India', filled: false },
      { portfolio: 'Republic of Indonesia', filled: false },
      { portfolio: 'Islamic Republic of Iran', filled: false },
      { portfolio: 'Republic of Iraq', filled: false },
      { portfolio: 'Ireland', filled: false },
      { portfolio: 'State of Israel', filled: false },
      { portfolio: 'Italian Republic', filled: false },
      { portfolio: 'Japan', filled: false },
      { portfolio: 'Hashemite Kingdom of Jordan', filled: false },
      { portfolio: 'Republic of Kenya', filled: false },
      { portfolio: 'State of Kuwait', filled: false },
      { portfolio: 'Lebanese Republic', filled: false },
      { portfolio: 'State of Libya', filled: false },
      { portfolio: 'Malaysia', filled: false },
      { portfolio: 'Republic of Mali', filled: false },
      { portfolio: 'United Mexican States', filled: false },
      { portfolio: 'Kingdom of Morocco', filled: false },
      { portfolio: 'Kingdom of the Netherlands', filled: false },
      { portfolio: 'New Zealand', filled: false },
      { portfolio: 'Federal Republic of Nigeria', filled: false },
      { portfolio: 'Kingdom of Norway', filled: false },
      { portfolio: 'Islamic Republic of Pakistan', filled: false },
      { portfolio: 'Republic of Peru', filled: false },
      { portfolio: 'Republic of the Philippines', filled: false },
      { portfolio: 'Republic of Poland', filled: false },
      { portfolio: 'State of Qatar', filled: false },
      { portfolio: 'Republic of Korea', filled: false },
      { portfolio: 'Romania', filled: false },
      { portfolio: 'Russian Federation', filled: false },
      { portfolio: 'Kingdom of Saudi Arabia', filled: false },
      { portfolio: 'Republic of Senegal', filled: false },
      { portfolio: 'Republic of Singapore', filled: false },
      { portfolio: 'Federal Republic of Somalia', filled: false },
      { portfolio: 'Republic of South Africa', filled: false },
      { portfolio: 'Kingdom of Spain', filled: false },
      { portfolio: 'Democratic Socialist Republic of Sri Lanka', filled: false },
      { portfolio: 'Republic of the Sudan', filled: false },
      { portfolio: 'Kingdom of Sweden', filled: false },
      { portfolio: 'Swiss Confederation', filled: false },
      { portfolio: 'Syrian Arab Republic', filled: false },
      { portfolio: 'Kingdom of Thailand', filled: false },
      { portfolio: 'Republic of Tunisia', filled: false },
      { portfolio: 'Republic of Türkiye', filled: false },
      { portfolio: 'Ukraine', filled: false },
      { portfolio: 'United Arab Emirates', filled: false },
      { portfolio: 'United Kingdom of Great Britain and Northern Ireland', filled: false },
      { portfolio: 'United States of America', filled: false },
      { portfolio: 'Bolivarian Republic of Venezuela', filled: false },
      { portfolio: 'Socialist Republic of Viet Nam', filled: false },
      { portfolio: 'Republic of Yemen', filled: false },
      { portfolio: 'Republic of Zambia', filled: false },
    ],
    eb: [
      { name: 'Priyanshu Biswas', position: 'Co-Chairperson', image: '/assets/eb/disec/priyanshu.jpeg' },
      { name: 'Zaina Rao', position: 'Co-Chairperson', image: '/assets/eb/disec/zaina.jpeg' },
      { name: 'Aahil K', position: 'Vice-Chairperson', image: '/assets/eb/disec/aahil.png' },
    ]
  },

  unhrc: {
    name: 'UNHRC',
    description: '',
    agenda: 'Discussing the regulation of emerging Neurotechnologies in relation to mental integrity and autonomy.',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'Argentina', filled: false },
      { portfolio: 'Brazil', filled: false },
      { portfolio: 'Chile', filled: false },
      { portfolio: 'Colombia', filled: false },
      { portfolio: 'Peru', filled: false },
      { portfolio: 'Ecuador', filled: false },
      { portfolio: 'Bolivia', filled: false },
      { portfolio: 'Paraguay', filled: false },
      { portfolio: 'Uruguay', filled: false },
      { portfolio: 'Mexico', filled: false },
      { portfolio: 'United States', filled: false },
      { portfolio: 'Canada', filled: false },
      { portfolio: 'Guatemala', filled: false },
      { portfolio: 'Honduras', filled: false },
      { portfolio: 'El Salvador', filled: false },
      { portfolio: 'Nicaragua', filled: false },
      { portfolio: 'Costa Rica', filled: false },
      { portfolio: 'Panama', filled: false },
      { portfolio: 'United Kingdom', filled: false },
      { portfolio: 'Ireland', filled: false },
      { portfolio: 'France', filled: false },
      { portfolio: 'Germany', filled: false },
      { portfolio: 'Spain', filled: false },
      { portfolio: 'Italy', filled: false },
      { portfolio: 'Poland', filled: false },
      { portfolio: 'Hungary', filled: false },
      { portfolio: 'Romania', filled: false },
      { portfolio: 'Ukraine', filled: false },
      { portfolio: 'Sweden', filled: false },
      { portfolio: 'Norway', filled: false },
      { portfolio: 'Netherlands', filled: false },
      { portfolio: 'Belgium', filled: false },
      { portfolio: 'Portugal', filled: false },
      { portfolio: 'Turkey', filled: false },
      { portfolio: 'Russia', filled: false },
      { portfolio: 'Georgia', filled: false },
      { portfolio: 'India', filled: false },
      { portfolio: 'Pakistan', filled: false },
      { portfolio: 'Bangladesh', filled: false },
      { portfolio: 'Nepal', filled: false },
      { portfolio: 'Sri Lanka', filled: false },
      { portfolio: 'Afghanistan', filled: false },
      { portfolio: 'China', filled: false },
      { portfolio: 'Japan', filled: false },
      { portfolio: 'South Korea', filled: false },
      { portfolio: 'Indonesia', filled: false },
      { portfolio: 'Malaysia', filled: false },
      { portfolio: 'Philippines', filled: false },
      { portfolio: 'Thailand', filled: false },
      { portfolio: 'Vietnam', filled: false },
      { portfolio: 'Egypt', filled: false },
      { portfolio: 'Morocco', filled: false },
      { portfolio: 'Algeria', filled: false },
      { portfolio: 'Tunisia', filled: false },
      { portfolio: 'Libya', filled: false },
      { portfolio: 'Sudan', filled: false },
      { portfolio: 'Ethiopia', filled: false },
      { portfolio: 'Kenya', filled: false },
      { portfolio: 'Uganda', filled: false },
      { portfolio: 'Tanzania', filled: false },
      { portfolio: 'Rwanda', filled: false },
      { portfolio: 'South Africa', filled: false },
      { portfolio: 'Nigeria', filled: false },
      { portfolio: 'Ghana', filled: false },
      { portfolio: 'Senegal', filled: false },
      { portfolio: 'Saudi Arabia', filled: false },
      { portfolio: 'Iran', filled: false },
      { portfolio: 'Jordan', filled: false },
      { portfolio: 'Israel', filled: false },
      { portfolio: 'New Zealand', filled: false },
      { portfolio: 'Australia', filled: false },
      { portfolio: 'Switzerland', filled: false },
      { portfolio: 'Finland', filled: false },
      { portfolio: 'Denmark', filled: false },
      { portfolio: 'Singapore', filled: false },
      { portfolio: 'United Arab Emirates', filled: false },
      { portfolio: 'Maldives', filled: false },
      { portfolio: 'Mauritius', filled: false },
      { portfolio: 'Iceland', filled: false },
      { portfolio: 'Fiji', filled: false },
    ],
    eb: [
      { name: 'Aabid Maldar', position: 'Co-Chairperson', image: '/assets/eb/unhrc/aabid.png' },
      { name: 'Yeshwanth Reddy', position: 'Co-Chairperson', image: '/assets/eb/unhrc/yeshwanth.jpeg' },
      { name: 'Ashlin Jermine George', position: 'Vice-Chairperson', image: '/assets/eb/unhrc/ashlin.jpeg' },
      { name: 'Devyansh Behera', position: 'Moderator', image: '/assets/eb/unhrc/devyansh.png' },
    ],
  },

  aippm: {
    name: 'AIPPM',
    description: '',
    agenda: 'Deliberating upon the electoral landscape in India with reference to the upcoming census and subsequent delimitation',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'Narendra Modi', filled: false },
      { portfolio: 'Amit Shah', filled: false },
      { portfolio: 'Tejasvi Surya', filled: false },
      { portfolio: 'Arjun Ram Meghwal', filled: false },
      { portfolio: 'Kiren Rijju', filled: false },
      { portfolio: 'Kangana Ranaut', filled: false },
      { portfolio: 'Yaduveer Krishnadatta Chamaraja Wadiyar', filled: false },
      { portfolio: 'Dr. C.N Manjunath', filled: false },
      { portfolio: 'Nitin Gadkari', filled: false },
      { portfolio: 'Suresh Gopi', filled: false },
      { portfolio: 'Anurag Thakur', filled: false },
      { portfolio: 'Nishikant Dubey', filled: false },
      { portfolio: 'Piyush Goyal', filled: false },
      { portfolio: 'Jyotiraditya Scindia', filled: false },
      { portfolio: 'Gajendra Singh Shekhawa', filled: false },
      { portfolio: 'Shrikant shinde', filled: false },
      { portfolio: 'Lovely Anand', filled: false },
      { portfolio: 'Ajay Kumar Mandal', filled: false },
      { portfolio: 'Chirag Paswan', filled: false },
      { portfolio: 'Chandra Prakash Choudhary', filled: false },
      { portfolio: 'Hardeep Singh Puri', filled: false },
      { portfolio: 'Rajnath Singh', filled: false },
      { portfolio: 'H. D. Kumaraswamy', filled: false },
      { portfolio: 'Dharmendra Pradhan', filled: false },
      { portfolio: 'Shivraj Singh Chouhan', filled: false },
      { portfolio: 'Mansukh L. Mandaviya', filled: false },
      { portfolio: 'Ashwini Vaishnaw', filled: false },
      { portfolio: 'Rahul Gandhi', filled: false },
      { portfolio: 'Dr. Shashi Tharoor', filled: false },
      { portfolio: 'Gaurav Gogoi', filled: false },
      { portfolio: 'K.C Venugopal', filled: false },
      { portfolio: 'Priyanka Gandhi Vadra', filled: false },
      { portfolio: 'Charanjit Singh Channi', filled: false },
      { portfolio: 'Karti P Chidambaram', filled: false },
      { portfolio: 'Manish Tewari', filled: false },
      { portfolio: 'Mahua Moitra', filled: false },
      { portfolio: 'Kanimozhi Karunanidhi', filled: false },
      { portfolio: 'Dayanidhi Maran', filled: false },
      { portfolio: 'Supriya Sule', filled: false },
      { portfolio: 'Akhilesh Yadav', filled: false },
      { portfolio: 'Dimple Yadav', filled: false },
      { portfolio: 'Asaduddin Owaisi', filled: false },
      { portfolio: 'Arvind Sawant', filled: false },
      { portfolio: 'E.T Mohammed Basheer', filled: false },
      { portfolio: 'Engineer Rashid', filled: false },
      { portfolio: 'Pappu Yadav', filled: false },
      { portfolio: 'Aga syed Ruhullah Mehdi', filled: false },
      { portfolio: 'A.M Ariff', filled: false },
      { portfolio: 'Joba Majhi', filled: false },
      { portfolio: 'Rajkumar Roat', filled: false },
      { portfolio: 'Muhammed Hamdullah Syed', filled: false },
      { portfolio: 'Priyanka Jarkiholi', filled: false },
      { portfolio: 'Deepender Singh Hooda', filled: false },
    ],
    eb: [],
  },

  ipc: {
    name: 'IPC',
    description: '',
    agenda: 'No Agenda.',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'The Washington Post', filled: false },
      { portfolio: 'The Economist', filled: false },
      { portfolio: 'National Review', filled: false },
      { portfolio: 'Al Jazeera', filled: false },
      { portfolio: 'The Hindu', filled: false },
      { portfolio: 'Swatantra', filled: false },
      { portfolio: 'The Deccan Herald', filled: false },
      { portfolio: 'BBC', filled: false },
      { portfolio: 'TASS', filled: false },
      { portfolio: 'African News Agency', filled: false },
      { portfolio: 'Reuters', filled: false },
      { portfolio: 'The Jacobin', filled: false },
      { portfolio: 'The New York Times', filled: false },
      { portfolio: 'The Daily Telegraph', filled: false },
      { portfolio: 'The Wall Street Journal', filled: false },
      { portfolio: 'The South China Post', filled: false },
      { portfolio: 'Bloomberg', filled: false },
      { portfolio: 'The Guardian', filled: false },
      { portfolio: 'Mother Jones', filled: false },
      { portfolio: 'Reason', filled: false },
      { portfolio: 'The Daily Wire', filled: false },
      { portfolio: 'Vox', filled: false },
      { portfolio: 'The Atlantic', filled: false },
      { portfolio: 'Sankei Shimbun', filled: false },
      { portfolio: 'Doordarshan', filled: false },
      { portfolio: 'Le Figaro', filled: false },
      { portfolio: 'Junge Freiheit', filled: false },
      { portfolio: 'Neue Zürcher Zeitung', filled: false },
      { portfolio: 'Xinhua News Agency', filled: false },
      { portfolio: 'El Mercurio', filled: false },
    ],
    eb: [
      { name: 'Shanmukha Siva Mythreya', position: 'International Head of Press', image: '/assets/eb/ipc/shanmukha.jpeg' },
    ],
  },

  unsc: {
    name: 'UNSC',
    description: '',
    agenda: 'De-escalation of US-Iran War with special emphasis on the Strait of Hormuz Freeze date: June 7, 2026, Israeli strikes on Hezbollah',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'United States', filled: false },
      { portfolio: 'China', filled: false },
      { portfolio: 'France', filled: false },
      { portfolio: 'Russia', filled: false },
      { portfolio: 'United Kingdom', filled: false },
      { portfolio: 'Japan', filled: false },
      { portfolio: 'Greece', filled: false },
      { portfolio: 'Denmark', filled: false },
      { portfolio: 'Somalia', filled: false },
      { portfolio: 'Panama', filled: false },
      { portfolio: 'Algeria', filled: false },
      { portfolio: 'Sierra Leone', filled: false },
      { portfolio: 'Guyana', filled: false },
      { portfolio: 'Iran', filled: false },
      { portfolio: 'Israel', filled: false },
      { portfolio: 'Saudi Arabia', filled: false },
      { portfolio: 'United Arab Emirates', filled: false },
      { portfolio: 'Oman', filled: false },
      { portfolio: 'Qatar', filled: false },
      { portfolio: 'Kuwait', filled: false },
      { portfolio: 'Bahrain', filled: false },
      { portfolio: 'Iraq', filled: false },
      { portfolio: 'Lebanon', filled: false },
      { portfolio: 'Turkey', filled: false },
      { portfolio: 'Pakistan', filled: false },
      { portfolio: 'India', filled: false },
      { portfolio: 'South Korea', filled: false },
      { portfolio: 'Singapore', filled: false },
      { portfolio: 'Egypt', filled: false },
      { portfolio: 'Italy', filled: false },
    ],
    eb: [
      { name: 'Eshaan Chowdary', position: 'Head-Chairperson', image: '/assets/eb/unsc/eshaan.jpeg' },
      { name: 'Jishnu Adidam', position: 'Vice-Chairperson', image: '/assets/eb/unsc/jishnu.jpeg' },
      { name: 'Aarav Sinha', position: 'Vice-Chairperson', image: '/assets/eb/unsc/aarav.jpeg' },
    ],
  },

  icrc: {
    name: 'ICRC',
    description: '',
    agenda: 'Examining the Role of the International Committee of the Red Cross in Providing Humanitarian Assistance and Protection to Civilians in the Gaza Strip',
    backgroundGuideUrl: null,
    matrix: [
      { portfolio: 'Israel', filled: false },
      { portfolio: 'Palestine', filled: false },
      { portfolio: 'Hamas', filled: false },
      { portfolio: 'Egypt', filled: false },
      { portfolio: 'Jordan', filled: false },
      { portfolio: 'Lebanon', filled: false },
      { portfolio: 'United States', filled: false },
      { portfolio: 'Saudi Arabia', filled: false },
      { portfolio: 'France', filled: false },
      { portfolio: 'Russia', filled: false },
      { portfolio: 'China', filled: false },
      { portfolio: 'Qatar', filled: false },
      { portfolio: 'United Kingdom', filled: false },
      { portfolio: 'United Arab Emirates', filled: false },
      { portfolio: 'Turkey', filled: false },
      { portfolio: 'Iran', filled: false },
      { portfolio: 'Kuwait', filled: false },
      { portfolio: 'Bahrain', filled: false },
      { portfolio: 'Oman', filled: false },
      { portfolio: 'Iraq', filled: false },
      { portfolio: 'Syria', filled: false },
      { portfolio: 'Germany', filled: false },
      { portfolio: 'Italy', filled: false },
      { portfolio: 'Spain', filled: false },
      { portfolio: 'Netherlands', filled: false },
      { portfolio: 'Belgium', filled: false },
      { portfolio: 'Sweden', filled: false },
      { portfolio: 'Norway', filled: false },
      { portfolio: 'Switzerland', filled: false },
      { portfolio: 'Ireland', filled: false },
      { portfolio: 'India', filled: false },
      { portfolio: 'Pakistan', filled: false },
      { portfolio: 'Indonesia', filled: false },
      { portfolio: 'Malaysia', filled: false },
      { portfolio: 'Bangladesh', filled: false },
      { portfolio: 'Canada', filled: false },
      { portfolio: 'Japan', filled: false },
      { portfolio: 'Australia', filled: false },
      { portfolio: 'South Africa', filled: false },
      { portfolio: 'Brazil', filled: false },
    ],
    eb: [
      { name: 'Brihan Shankar', position: 'Head-Chairperson', image: '/assets/eb/icrc/brihan.jpeg' },
      { name: 'Arul S.', position: 'Vice-Chairperson', image: '/assets/eb/icrc/arul.jpeg' },
      { name: 'Harsha Aditya', position: 'Vice-Chairperson', image: '/assets/eb/icrc/harsha.jpeg' },
    ],
  },

  ccc: {
    name: 'CCC',
    description: '',
    agenda: 'Agenda: Project 571 Freeze Date: 8th September 1971 (0600)',
    backgroundGuideUrl: null,
    matrix: [],
    eb: [],
  },
}
